# Install cert-manager
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: falco-security
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: falco-security
  project: default
  source:
    path: falcosecurity
    chart: falco
    repoURL: https://falcosecurity.github.io/charts
    targetRevision: v0.26.1
    helm:
      releaseName: falco
      parameters:
        - name: "serviceMonitor.enabled"
          value: "true"
        - name: "grafana.dashboards.enabled"
          value: "true"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
