# Install cert-manager
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: metrics-server-helm-chart
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: metrics-server
  project: default
  source:
    path: metrics-server
    chart: metrics-server
    repoURL: https://kubernetes-sigs.github.io/metrics-server
    targetRevision: v3.12.2
    helm:
      releaseName: metrics-server
      parameters:
        - name: "metrics.enabled"
          value: "true"
        - name: "args[0]"
          value: "--kubelet-insecure-tls"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
