apiVersion: apps/v1
kind: Deployment
metadata:
  name: s5cmd-tools
  namespace: rook-ceph # namespace:cluster
  labels:
    app: s5cmd-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s5cmd-tools
  template:
    metadata:
      labels:
        app: s5cmd-tools
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 2016
        runAsGroup: 2016
      serviceAccountName: rook-ceph-default
      imagePullSecrets:
        - name: ceph-bucket
      restartPolicy: Always
      containers:
        - name: s5cmd-tools
          image: peakcom/s5cmd:v2.3.0
          command:
            - /aws/s5cmd --help
          imagePullPolicy: IfNotPresent
          tty: true
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: ceph-bucket
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: ceph-bucket
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_HOST
              valueFrom:
                configMapKeyRef:
                  name: ceph-bucket
                  key: BUCKET_HOST
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: ceph-bucket
                  key: BUCKET_PORT
            - name: BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: ceph-bucket
                  key: BUCKET_NAME
          volumeMounts:
            - mountPath: /etc/ceph
              name: ceph-config
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
      volumes:
        - name: ceph-config
          emptyDir: {}
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 5
