apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/name: prometheus-kube-state-metrics-hack
    app.kubernetes.io/part-of: kube-state-metrics
    jobLabel: node-exporter
    release: prometheus
  name: prometheus-kube-state-metrics-hack
  namespace: monitoring
spec:
  attachMetadata:
    node: false
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      honorLabels: true
      honorTimestamps: true
      interval: 10s
      port: http
      scheme: http
      tlsConfig:
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecureSkipVerify: true
      trackTimestampsStaleness: true
  selector:
    matchLabels:
      app.kubernetes.io/instance: monitoring
      app.kubernetes.io/name: kube-state-metrics
