apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/name: prometheus-node-exporter-hack
    app.kubernetes.io/part-of: prometheus-node-exporter
    jobLabel: node-exporter
    release: prometheus
  name: prometheus-prometheus-node-exporter-hack
  namespace: monitoring
spec:
  attachMetadata:
    node: false
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      honorLabels: true
      honorTimestamps: true
      interval: 10s
      port: http-metrics
      scheme: http
      tlsConfig:
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecureSkipVerify: true
      trackTimestampsStaleness: true
  jobLabel: jobLabel
  selector:
    matchLabels:
      app.kubernetes.io/instance: monitoring
      app.kubernetes.io/name: prometheus-node-exporter
