# Install nginx-gateway-fabric
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: gateway
  project: default
  source:
    path: gloo
    chart: gloo
    repoURL: https://storage.googleapis.com/solo-public-helm
    targetRevision: v1.18.12
    helm:
      releaseName: gloo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
