apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: provisioner
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: provisioner
  project: default
  source:
    path: deploy/chart
    chart: local-path-provisioner
    repoURL: https://github.com/rancher/local-path-provisioner
    targetRevision: "v0.0.31"
    helm:
      releaseName: local-path-provisioner
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
