# install the Rook Ceph Operator
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: local-path-storage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: local-path-storage
  project: default
  source:
    path: app-of-infra/infra/local-path-storage
    repoURL: "https://github.com/mtyler/kinfra"
    targetRevision: vagrant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
