# install the Rook Ceph Operator
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: { ? { .Values.spec.destination.server } }
    namespace: rook-ceph
  project: default
  source:
    path: rook-ceph
    chart: rook-ceph
    repoURL: https://charts.rook.io/release
    targetRevision: 1.16
    helm:
      releaseName: rook-ceph
      parameters:
      - name: "csi.enableCSIHostNetwork"
        value: "true"
      - name: "csi.enableCephfsSnapshotter"
        value: "false"
      - name: "csi.enableNFSSnapshotter"
        value: "false"
      - name: "csi.enableRBDSnapshotter"
        value: "false"
      - name: "csi.provisionerReplicas"
        value: "1"
      - name: "csi.seviceMonitor.enabled"
        value: "true"
      - name: "enableDiscoveryDaemon"
        value: "true"
      - name: "monitoring.enabled"
        value: "true"
